/* eslint-disable react/jsx-key */
import { Spacer } from "@nextui-org/react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import CustomNavbar from "./src/components/CustomNavbar";
import EventCard from "./src/components/EventCard";
import EventCarousel from "./src/components/EventCarousel";
import ProfileCard from "./src/components/ProfileCard";
import ProfileCarousel from "./src/components/ProfileCarousel";
import InterestCarousel from "./src/components/InterestCarousel";
import useStorage from "./src/hooks/storage";
import { LoginContext } from "./_app";
import { allHobbies, fakeHobbies, fakeUser, event, eventOnline, profile } from "./constants/fakeData";
import { useContext } from "react";


const a = <EventCard info={event} />;
const b = <EventCard info={eventOnline} />;
const c = <ProfileCard info={profile} />;

const Home: NextPage = () => {
  const { user } = useContext(LoginContext);
  const props = {
    userProfile: user,
  }; // TODO: get props from user here
  return (
    <div className={styles.container}>
      <Head>
        <title>LetsPlay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CustomNavbar {...props} />
      <Spacer y={1} />

      <InterestCarousel tags={fakeHobbies} alltags={allHobbies} />
      <Spacer y={1} />
      <ProfileCarousel profiles={[c, c, c, c, c, c]} />
      <Spacer y={1} />
      <EventCarousel events={[a, b, a, a, b]} allTags={allHobbies} />
      <Spacer y={1} />
    </div>
  );
};

export default Home;
